#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display Information about subdomains

domain_info () {
if [ $# -eq 2 ]
then
    sub="$2"
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain '$sub' is a "$4" record and points to "$NF""}'

elif [ $# -eq 1 ]
then
    subs=('www' 'lb-01' 'web-01' 'web-02')
    for each in "${subs[@]}"
    do
        dig $each.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain '$each' is a "$4" record and points to "$NF""}'
    done
fi
}

domain_info $1 $2
