#!/usr/bin/env bash
# script displaying infinite message and catch SIGTERM signal to print other message
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
