#!/usr/bin/env bash
#Script using nested if statements
file="School"
if [ -e $file ]
then
	echo "$file file exists"

	if [ -s $file ]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f $file ]
	then
		echo "$file file is regular file"
	fi
else
	echo "$file file does not  exist"
fi
